# escape=`
FROM mcr.microsoft.com/windows/servercore:1903 AS downloader

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV ES_VERSION="5.0.2" `
    ES_HOME="C:\eventstore"

# ENV chocolateyUseWindowsCompression false

# RUN powershell -Command `
#         iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')); `
#         choco feature disable --name showDownloadProgress

# RUN choco install eventstore-oss

RUN Invoke-WebRequest "https://eventstore.org/downloads/win/EventStore-OSS-Win-v$($env:ES_VERSION).zip" -OutFile 'eventstore.zip' -UseBasicParsing; `
    Expand-Archive eventstore.zip -DestinationPath $env:ES_HOME ;

FROM mcr.microsoft.com/windows/servercore:1903
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

ENV ES_VERSION="5.0.2" `
    ES_HOME="C:\eventstore"

EXPOSE 1113 2113

VOLUME C:\Data
VOLUME C:\Logs

RUN New-Item -Path Config -ItemType Directory | Out-Null

HEALTHCHECK --start-period=10s --interval=5s --timeout=5s CMD powershell -command `
    try { `
        $response = Invoke-WebRequest 'http://localhost:2113/stats' -UseBasicParsing; `
        if ($response.StatusCode -eq 200) { return 0 } `
        else { return 1 }; `
    } catch { return 1 }

WORKDIR $ES_HOME
COPY --from=downloader C:\eventstore\ .
COPY eventstore.conf .\Config\

# Run Service
SHELL ["cmd", "/S", "/C"]
CMD C:\eventstore\EventStore.ClusterNode.exe --db /Data --log /Logs --config=C:\eventstore\Config\eventstore.conf
